travis:
  secure:
    BINSTAR_TOKEN: CsZclOVe1p9/k20nYEW2cYsHLZwB4Di6Jx7/7s1hwlNDOQh7FWW4BvEYmxWnihj13jB1vx81hV0bk8pC6HtUhAMWWHOa5ubiKB+2CCIO1NT1mjWzOed5gTMowk7eQgJzBKqKrKSNJ0G2lfBZkJCA9IY85puHiK1hlRv1V4p8l5WBHAPgyePXsoQglQHSzxcGhyk9/2vGiINGKP3NvlzDOl4pHTBIZTo3IEBzIzcPDzr+9lUlMFuMnvaseK6ywtEtRCwHRvfFybON0b2vvY+O2ZDjUp7aTf9leUG1H8MB6YojNsTxnH0g57RaMw+LBFU1Hkne6cc4sPMeWWGqG9J0Xa7YLy/Q/ZK0RfVNWzzyNEJPqNybY9ugGAVf+1vvp7GGJ+haZ8egUi1U7bzVURBnD6CFGWvHh9Yatgvy1ujQFzAvH+TKuPwoBlQL6t8eFZzrAjfDKlaz1Y6V3AeCUDEAo6Pki/giTjX4Nl+2aseDXGu/zpGFi1t0xKGDIlHoU1ss/qM4NmrloRoaha3COBB0ijThK248sc0+pLU1dCu41Dt1W89lcv1najWgKFcMb3J/UJYrZzXc8KeY35r2xUmIB6Txo1V8DuIojtg637N7Rt1FM0/Xv1grqMxzN3FEOHsaRSheKbj8W0Tb2aos3PfRhpnUq5frW0cmINaVlKUbrI0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
